apiVersion: greenhouse.sap/v1alpha1
kind: PluginDefinition
metadata:
  name: controlplane-operations
spec:
  version: 1.0.4
  displayName: Controlplane operations bundle
  description: Operations bundle for Controlane clusters
  docMarkDownUrl: https://raw.githubusercontent.com/cloudoperators/controlplane-operations/main/README.md
  icon: https://raw.githubusercontent.com/cloudoperators/controlplane-operations/main/charts/controlplane-operations/kubernetes-logo.png
  helmChart:
    name: controlplane-operations
    repository: oci://ghcr.io/cloudoperators/controlplane-operations/charts
    version: 1.0.4
  options:
    - name: prometheusRules.create
      description: Create Prometheus rules
      required: false
      default: true
      type: bool
    - name: prometheusRules.ruleSelector
      description: Selector for Prometheus rules to be picked up by the Prometheus operator. List of key-value pairs.
      required: false
      type: list
    - name: prometheusRules.additionalRuleLabels
      description: Additional labels to be added every Prometheus rule. E.g support_group, service
      required: false
      type: map
    - name: dashboards.create
      description: Create Plutono dashboards
      required: false
      default: false
      type: bool
    - name: dashboards.dashboardSelector
      description: Selector for dashboards to be picked up by the Plutono. List of key-value pairs.
      required: false
      type: list
