header:
  license:
    spdx-id: Apache-2.0
    content: |
      SPDX-FileCopyrightText: [year] SAP SE or an SAP affiliate company and Greenhouse contributors
      SPDX-License-Identifier: Apache-2.0
    pattern: |
      SPDX-FileCopyrightText: [0-9]+ SAP SE or an SAP affiliate company and Greenhouse contributors
      SPDX-License-Identifier: Apache-2\.0

  paths: # `paths` are the path list that will be checked (and fixed) by license-eye, default is ['**'].
    - '**'

  paths-ignore:
    - '.github/**'
    - '.reuse/dep5'
    - 'LICENSES/*.txt'
    - '**/*.md'
    - 'LICENSE'
    - '**/*.gitignore'
    - '**/*.helmignore'
    - '**/*.tpl'
    - '**/.gitkeep'
    - '**/*.txt'
    - '*Dockerfile*'
    - 'Makefile'
    - 'README.md.gotmpl'
    - 'charts/**/**/*.yaml' # license headers on helm templates are causing issues 

  comment: on-failure
  
  # license-location-threshold specifies the index threshold where the license header can be located,
  # after all, a "header" cannot be TOO far from the file start.
  license-location-threshold: 80

  language:
    JSX: 
      extensions:
        - ".jsx"
      comment_style_id: SlashAsterisk
