groups:
- name: controlplane-pvc
  rules:
    - record: kubelet_volume_stats_available_percent
      expr: (min by (persistentvolumeclaim, namespace) (100 * kubelet_volume_stats_available_bytes / kubelet_volume_stats_capacity_bytes))

- name: controlplane.pvc.alerts
  rules:
{{- if not (.Values.prometheusRules.disabled.KubernetesPVCNoSpaceLeft | default false) }}
  - alert: KubernetesPVCNoSpaceLeft
    expr: kubelet_volume_stats_available_percent < 10
    for: {{ dig "KubernetesPVCNoSpaceLeft" "for" "10m" .Values.prometheusRules }}
    labels:
      severity: {{ dig "KubernetesPVCNoSpaceLeft" "severity" "info" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/KubernetesPVCNoSpaceLeft.md
      {{ include "controlplane-operations.additionalRuleLabels" . }}
    annotations:
      description: "The PVC `{{`{{ $labels.namespace }}`}}`/`{{`{{ $labels.persistentvolumeclaim }}`}}` is almost full. Increase or delete files."
      summary: "PVC `{{`{{ $labels.namespace }}`}}`/`{{`{{ $labels.persistentvolumeclaim }}`}}` free space is less than 10%."
{{- end }}

{{- if not (.Values.prometheusRules.disabled.KubernetesPVCNoSpaceLeft | default false) }}
  - alert: KubernetesPVCNoSpaceLeft
    expr: kubelet_volume_stats_available_percent < 2
    for: {{ dig "KubernetesPVCNoSpaceLeft" "for" "10m" .Values.prometheusRules }}
    labels:
      severity: {{ dig "KubernetesPVCNoSpaceLeft" "severity" "warning" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/KubernetesPVCNoSpaceLeft.md
      {{ include "controlplane-operations.additionalRuleLabels" . }}
    annotations:
      description: "The PVC `{{`{{ $labels.namespace }}`}}`/`{{`{{ $labels.persistentvolumeclaim }}`}}` is full. Programs will stop working if relying upon free storage."
      summary: "PVC `{{`{{ $labels.namespace }}`}}`/`{{`{{ $labels.persistentvolumeclaim }}`}}` usage is over 98%."
{{- end }}
