groups:
- name: controlplane-backup
  rules:
{{- if not (.Values.prometheusRules.disabled.EtcdKCPBackupCrashLoopBackOff | default false) }}
  - alert: EtcdKCPBackupCrashLoopBackOff
    expr: >
      max_over_time(
        kube_pod_container_status_waiting_reason{
          pod=~"etcd-kcp-backup-[a-z0-9]{8,10}-[a-z0-9]{5}",
          reason="CrashLoopBackOff"
        }[5m]
      ) == 1
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "EtcdKCPBackupCrashLoopBackOff" "severity" "info" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/EtcdKCPBackupCrashLoopBackOff.md
      service: {{ dig "EtcdKCPBackupCrashLoopBackOff" "service" .Values.prometheusRules.defaultService .Values.prometheusRules }}
      support_group: {{ dig "EtcdKCPBackupCrashLoopBackOff" "support_group" .Values.prometheusRules.defaultSupportGroup .Values.prometheusRules }}
    annotations:
      description: etcd KCP backup Pod {{`{{ $labels.namespace }}`}}/{{`{{ $labels.pod }}`}} on cluster {{`{{ $labels.cluster }}`}} is in CrashLoopBackOff. Check pod logs and events for more details.
      summary: etcd KCP backup Pod {{`{{ $labels.pod }}`}} on {{`{{ $labels.cluster }}`}} is in CrashLoopBackOff.
{{- end }}

{{- if not (.Values.prometheusRules.disabled.EtcdKCPBackupRestartRate | default false) }}
  - alert: EtcdKCPBackupRestartRate
    expr: >
      rate(kube_pod_container_status_restarts_total{pod=~"etcd-kcp-backup-[a-z0-9]{8,10}-[a-z0-9]{5}"}[15m]) > 0
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "EtcdKCPBackupRestartRate" "severity" "info" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/EtcdKCPBackupRestartRate.md
      service: {{ dig "EtcdKCPBackupRestartRate" "service" .Values.prometheusRules.defaultService .Values.prometheusRules }}
      support_group: {{ dig "EtcdKCPBackupRestartRate" "support_group" .Values.prometheusRules.defaultSupportGroup .Values.prometheusRules }}
    annotations:
      description: etcd KCP backup Pod {{`{{ $labels.namespace }}`}}/{{`{{ $labels.pod }}`}} on cluster {{`{{ $labels.cluster }}`}} is restarting frequently. Check pod logs and events for more details.
      summary: etcd KCP backup Pod {{`{{ $labels.pod }}`}} on {{`{{ $labels.cluster }}`}} is restarting frequently.
{{- end }}

{{- if not (.Values.prometheusRules.disabled.EtcdKCPBackupFailure | default false) }}
  - alert: EtcdKCPBackupFailure
    expr: >
      etcdbr_snapshot_duration_seconds_count{kind="Full",succeeded="false"} > 0
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "EtcdKCPBackupFailure" "severity" "info" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/EtcdKCPBackupFailure.md
      service: {{ dig "EtcdKCPBackupFailure" "service" .Values.prometheusRules.defaultService .Values.prometheusRules }}
      support_group: {{ dig "EtcdKCPBackupFailure" "support_group" .Values.prometheusRules.defaultSupportGroup .Values.prometheusRules }}
    annotations:
      description: etcd KCP backup Pod {{`{{ $labels.namespace }}`}}/{{`{{ $labels.pod }}`}} with instance IP {{`{{ $labels.instance }}`}} failed full snapshot. Check pod logs and events for more details.
      summary: etcd KCP backup Pod {{`{{ $labels.pod }}`}} failed full snapshot.
{{- end }}

{{- if not (.Values.prometheusRules.disabled.EtcdKCPBackupSnapshotTooOld | default false) }}
  - alert: EtcdKCPBackupSnapshotTooOld
    expr: >
      (
        (time() - etcdbr_snapshot_latest_timestamp{kind="Full"}) > 24 * 3600
      )
      AND
      on()
      count(
        (time() - etcdbr_snapshot_latest_timestamp{kind="Full"}) > 24 * 3600
      ) > 2
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "EtcdKCPBackupSnapshotTooOld" "severity" "info" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/EtcdKCPBackupSnapshotTooOld.md
      service: {{ dig "EtcdKCPBackupSnapshotTooOld" "service" .Values.prometheusRules.defaultService .Values.prometheusRules }}
      support_group: {{ dig "EtcdKCPBackupSnapshotTooOld" "support_group" .Values.prometheusRules.defaultSupportGroup .Values.prometheusRules }}
    annotations:
      description: etcd KCP backup Pod {{`{{ $labels.namespace }}`}}/{{`{{ $labels.pod }}`}} with instance IP {{`{{ $labels.instance }}`}} has an outdated full snapshot. Check pod logs and events for more details.
      summary: etcd KCP backup Pod {{`{{ $labels.pod }}`}} has an outdated full snapshot.
{{- end }}
