groups:
- name: controlplane-remote.alerts
  rules:
{{- if not (.Values.prometheusRules.disabled.ArgoraUpdateInError | default false) }}
  - alert: ArgoraUpdateInError
    expr: >
      kube_customresource_status_state{customresource_kind="Update",customresource_group="argora.cloud.sap",state=~"Error"}
      == 1
    for: {{ dig "ArgoraUpdateInError" "for" "10m" .Values.prometheusRules }}
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "ArgoraUpdateInError" "severity" "warning" .Values.prometheusRules }}
      playbook: https://operations.global.cloud.sap/docs/support/playbook/argora-update-in-error/ #TODO: add playbook
      service: {{ dig "ArgoraUpdateInError" "service" .Values.prometheusRules.defaultService .Values.prometheusRules }}
      support_group: {{ dig "ArgoraUpdateInError" "supportGroup" .Values.prometheusRules.defaultSupportGroup .Values.prometheusRules }}
    annotations:
      description: "Argora Update CR status is in Error state for more than 10 minutes."
      summary: "Update CR in Error state."
{{- end }}

{{- if not (.Values.prometheusRules.disabled.ArgoraClusterImportInError | default false) }}
  - alert: ArgoraClusterImportInError
    expr: >
      kube_customresource_status_state{customresource_kind="ClusterImport",customresource_group="argora.cloud.sap",state=~"Error"}
      == 1
    for: {{ dig "ArgoraClusterImportInError" "for" "10m" .Values.prometheusRules }}
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "ArgoraClusterImportInError" "severity" "warning" .Values.prometheusRules }}
      playbook: https://operations.global.cloud.sap/docs/support/playbook/argora-clusterimport-in-error/ #TODO: add playbook
      service: {{ dig "ArgoraClusterImportInError" "service" .Values.prometheusRules.defaultService .Values.prometheusRules }}
      support_group: {{ dig "ArgoraClusterImportInError" "supportGroup" .Values.prometheusRules.defaultSupportGroup .Values.prometheusRules }}
    annotations:
      description: "Argora ClusterImport CR status is in Error state for more than 10 minutes."
      summary: "ClusterImport CR in Error state."
{{- end }}

{{- if not (.Values.prometheusRules.disabled.ArgoraPodNotReadyError | default false) }}
  - alert: ArgoraPodNotReadyError
    expr: >
      kube_pod_status_ready{pod=~"argora-controller-manager-.+",condition="true"} == 0
    for: {{ dig "ArgoraPodNotReadyError" "for" "5m" .Values.prometheusRules }}
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "ArgoraPodNotReadyError" "severity" "warning" .Values.prometheusRules }}
      playbook: https://operations.global.cloud.sap/docs/support/playbook/argora-pod-not-ready/ #TODO: add playbook
      service: {{ dig "ArgoraPodNotReadyError" "service" .Values.prometheusRules.defaultService .Values.prometheusRules }}
      support_group: {{ dig "ArgoraPodNotReadyError" "supportGroup" .Values.prometheusRules.defaultSupportGroup .Values.prometheusRules }}
    annotations:
      description: "Argora Pod is not ready for more than 5 minutes."
      summary: "Pod not ready."
{{- end }}

{{- if not (.Values.prometheusRules.disabled.ServerStuckInDiscovery | default false) }}
  - alert: ServerStuckInDiscovery
    expr: >
      kube_customresource_status_state{customresource_kind="Server",customresource_group="metal.ironcore.dev",state=~"Discovery"}
      == 1
    for: {{ dig "ServerStuckInDiscovery" "for" "15m" .Values.prometheusRules }}
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "ServerStuckInDiscovery" "severity" "warning" .Values.prometheusRules }}
      playbook: https://operations.global.cloud.sap/docs/support/playbook/server-stuck-in-discovery/ #TODO: add playbook
      service: {{ dig "ServerStuckInDiscovery" "service" .Values.prometheusRules.defaultService .Values.prometheusRules }}
      support_group: {{ dig "ServerStuckInDiscovery" "supportGroup" .Values.prometheusRules.defaultSupportGroup .Values.prometheusRules }}
    annotations:
      description: "Server is stuck in Discovery for more than 15 minutes."
      summary: "Server stuck in Discovery."
{{- end }}
