groups:
- name: controlplane-gardener
  rules:

### Gardener ###

{{- if not (.Values.prometheusRules.disabled.ShootReconciliationFailed | default false) }}
  - alert: ShootReconciliationFailed
    expr: garden_shoot_operation_states{operation="Reconcile"} != 1
    for: {{ dig "ShootReconciliationFailed" "for" "30m" .Values.prometheusRules }}
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "ShootReconciliationFailed" "severity" "warning" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/ShootReconciliationFailed.md
      service: {{ dig "ShootReconciliationFailed" "service" .Values.prometheusRules.defaultService .Values.prometheusRules }}
      support_group: {{ dig "ShootReconciliationFailed" "support_group" .Values.prometheusRules.defaultSupportGroup .Values.prometheusRules }}
    annotations:
      description: Shoot {{`{{ $labels.name }}`}} is not being reconciled successfully. Check the shoot's conditions and events for more details.
      summary: Shoot {{`{{ $labels.name }}`}} is not being reconciled successfully.
{{- end }}

{{- if not (.Values.prometheusRules.disabled.ShootConditionNotTrue | default false) }}
  - alert: ShootConditionNotTrue
    expr: max by(name) (garden_shoot_condition != 1)
    for: {{ dig "ShootConditionNotTrue" "for" "30m" .Values.prometheusRules }}
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "ShootConditionNotTrue" "severity" "warning" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/ShootConditionNotTrue.md
      service: {{ dig "ShootConditionNotTrue" "service" .Values.prometheusRules.defaultService .Values.prometheusRules }}
      support_group: {{ dig "ShootConditionNotTrue" "support_group" .Values.prometheusRules.defaultSupportGroup .Values.prometheusRules }}
    annotations:
      description: Shoot {{`{{ $labels.name }}`}} has a condition that is not True. Check the shoot's conditions and events for more details.
      summary: Shoot {{`{{ $labels.name }}`}} has a condition that is not True.
{{- end }}

{{- if not (.Values.prometheusRules.disabled.SeedConditionNotTrue | default false) }}
  - alert: SeedConditionNotTrue
    expr: max by(name) (garden_seed_condition != 1)
    for: {{ dig "SeedConditionNotTrue" "for" "30m" .Values.prometheusRules }}
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "SeedConditionNotTrue" "severity" "warning" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/SeedConditionNotTrue.md
      service: {{ dig "SeedConditionNotTrue" "service" .Values.prometheusRules.defaultService .Values.prometheusRules }}
      support_group: {{ dig "SeedConditionNotTrue" "support_group" .Values.prometheusRules.defaultSupportGroup .Values.prometheusRules }}
    annotations:
      description: Seed {{`{{ $labels.name }}`}} has a condition that is not True. Check the seed's conditions and events for more details.
      summary: Seed {{`{{ $labels.name }}`}} has a condition that is not True.
{{- end }}

{{- if not (.Values.prometheusRules.disabled.GardenletNotReady | default false) }}
  - alert: GardenletNotReady
    expr: garden_garden_condition{status="True"} != 1
    for: {{ dig "GardenletNotReady" "for" "30m" .Values.prometheusRules }}
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "GardenletNotReady" "severity" "warning" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/GardenletNotReady.md
      service: {{ dig "GardenletNotReady" "service" .Values.prometheusRules.defaultService .Values.prometheusRules }}
      support_group: {{ dig "GardenletNotReady" "support_group" .Values.prometheusRules.defaultSupportGroup .Values.prometheusRules }}
    annotations:
      description: Gardenlet on {{`{{ $labels.landscape }}`}} is not Ready. Check the gardenlet's conditions and events for more details.
      summary: Gardenlet on {{`{{ $labels.landscape }}`}} is not Ready.
{{- end }}

### Calico ###

{{- if not (.Values.prometheusRules.disabled.CalicoBgpNeighborSessionDown | default false) }}
  - alert: CalicoBgpNeighborSessionDown
    expr: sum by (node) (bird_protocol_up{proto="BGP",state="Established"}) < {{ .Values.prometheusRules.calico.bgpNeighborCount }}
    for: {{ dig "CalicoBgpNeighborSessionDown" "for" "30m" .Values.prometheusRules }}
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "CalicoBgpNeighborSessionDown" "severity" "warning" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/CalicoBgpNeighborSessionDown.md
      service: {{ dig "CalicoBgpNeighborSessionDown" "service" .Values.prometheusRules.defaultService .Values.prometheusRules }}
      support_group: {{ dig "CalicoBgpNeighborSessionDown" "support_group" .Values.prometheusRules.defaultSupportGroup .Values.prometheusRules }}
    annotations:
      description: Node {{`{{ $labels.node }}`}} has less than {{ .Values.prometheusRules.calico.bgpNeighborCount }} BGP neighbors. BGP peer is not established. Network datapath threatened! Switch upgrades or misconfiguration?
      summary: Node {{`{{ $labels.node }}`}} has less than {{ .Values.prometheusRules.calico.bgpNeighborCount }} BGP neighbors.
{{- end }}

{{- if not (.Values.prometheusRules.disabled.CalicoBgpNeighborSessionAllDown | default false) }}
  - alert: CalicoBgpNeighborSessionAllDown
    expr: sum by (node) (bird_protocol_up{proto="BGP",state="Established"}) == 0
    for: {{ dig "CalicoBgpNeighborSessionAllDown" "for" "10m" .Values.prometheusRules }}
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "CalicoBgpNeighborSessionAllDown" "severity" "warning" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/CalicoBgpNeighborSessionAllDown.md
      service: {{ dig "CalicoBgpNeighborSessionAllDown" "service" .Values.prometheusRules.defaultService .Values.prometheusRules }}
      support_group: {{ dig "CalicoBgpNeighborSessionAllDown" "support_group" .Values.prometheusRules.defaultSupportGroup .Values.prometheusRules }}
    annotations:
        description: Node {{`{{ $labels.node }}`}} has no BGP neighbors. Network datapath is down! Switch upgrades or misconfiguration?
        summary: Node {{`{{ $labels.node }}`}} has no BGP neighbors.
{{- end }}

{{- if not (.Values.prometheusRules.disabled.CalicoNodeMissing | default false) }}
  - alert: CalicoNodeMissing
    expr: count(up{job="kube-kubelet"} == 1) > count(_pod_to_daemonset{owner_name="calico-node"} == 1)
    for: {{ dig "CalicoNodeMissing" "for" "30m" .Values.prometheusRules }}
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "CalicoNodeMissing" "severity" "warning" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/CalicoNodeMissing.md
      service: {{ dig "CalicoNodeMissing" "service" .Values.prometheusRules.defaultService .Values.prometheusRules }}
      support_group: {{ dig "CalicoNodeMissing" "support_group" .Values.prometheusRules.defaultSupportGroup .Values.prometheusRules }}
    annotations:
        description: Calico is not running on all bare metal nodes. Network datapath threatened!
        summary: Calico is not running on all nodes.
{{- end }}

{{- if not (.Values.prometheusRules.disabled.CalicoNodeNotReady | default false) }}
  - alert: CalicoNodeNotReady
    expr: kube_pod_status_ready{namespace="kube-system",pod=~"calico-node-[a-zA-Z0-9]{5}",condition="false",type="shoot"} == 1
    for: {{ dig "CalicoNodeNotReady" "for" "30m" .Values.prometheusRules }}
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "CalicoNodeNotReady" "severity" "warning" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/CalicoNodeNotReady.md
      service: {{ dig "CalicoNodeNotReady" "service" .Values.prometheusRules.defaultService .Values.prometheusRules }}
      support_group: {{ dig "CalicoNodeNotReady" "support_group" .Values.prometheusRules.defaultSupportGroup .Values.prometheusRules }}
    annotations:
      description: Calico-Node Pod {{`{{ $labels.pod }}`}} on shoot {{`{{ $labels.shoot_name }}`}} is not Ready. Network datapath threatened!
      summary: Calico-Node Pod {{`{{ $labels.pod }}`}} on shoot {{`{{ $labels.shoot_name }}`}} is not Ready.
{{- end }}
