groups:
- name: controlplane-bond
  rules:
{{- if not (.Values.prometheusRules.disabled.NodeBondDegradedMain | default false) }}
  - alert: NodeBondDegradedMain
    expr: sum(node_bonding_active) by (master, node) < 2
    for: {{ dig "NodeBondDegradedMain" "for" "15m" .Values.prometheusRules }}
    labels:
      severity: {{ dig "NodeBondDegradedMain" "severity" "warning" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/NodeBondDegradedMain.md
      {{ include "controlplane-operations.additionalRuleLabels" . }}
    annotations:
      description: Bond `{{`{{ $labels.master }}`}}` on `{{`{{ $labels.node }}`}}` is degraded. Imminent network outage for this node.
      summary: Bond `{{`{{ $labels.master }}`}}` is degraded. Node network connectivity is not HA. Switch failover or upgrade will cause an outage!
{{- end }}

{{- if not (.Values.prometheusRules.disabled.NodeVirtualInterfaceDown | default false) }}
  - alert: NodeVirtualInterfaceDown
    expr: sum(node_network_up{device=~"bond.*|vlan.*"} == 0) by (node, device)
    for: {{ dig "NodeVirtualInterfaceDown" "for" "15m" .Values.prometheusRules }}
    labels:
      severity: {{ dig "NodeVirtualInterfaceDown" "severity" "warning" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/NodeVirtualInterfaceDown.md
      {{ include "controlplane-operations.additionalRuleLabels" . }}
    annotations:
      description: Interface `{{`{{ $labels.device }}`}}` on `{{`{{ $labels.node }}`}}` is down. Tenant network outage for this node.
      summary: Interface `{{`{{ $labels.device }}`}}` is down. Node network connectivity is degraded.
{{- end }}
