groups:
- name: controlplane.alerts
  rules:
    ### PVC usage ###
    - alert: KubernetesPVCNoSpaceLeft
      expr: kubelet_volume_stats_available_percent < 10
      for: 10m
      labels:
        tier: k8s
        support_group: '{{ if $labels.label_ccloud_support_group }}{{ $labels.label_ccloud_support_group }}{{ else }}containers{{ end }}'
        service: '{{ if $labels.label_ccloud_service }}{{ $labels.label_ccloud_service }}{{ else }}resources{{ end }}'
        severity: info
        context: storage
        meta: "PVC {{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }} free space is less than 10%."
        playbook: 'docs/support/playbook/kubernetes/pvc_usage'
      annotations:
        description: "The PVC {{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }} is almost full. Increase or delete files."
        summary: "PVC {{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }} free space is less than 10%."
    - alert: KubernetesPVCNoSpaceLeft
      expr: kubelet_volume_stats_available_percent < 2
      for: 10m
      labels:
        tier: k8s
        support_group: '{{ if $labels.label_ccloud_support_group }}{{ $labels.label_ccloud_support_group }}{{ else }}containers{{ end }}'
        service: '{{ if $labels.label_ccloud_service }}{{ $labels.label_ccloud_service }}{{ else }}resources{{ end }}'
        severity: warning
        context: storage
        meta: "PVC {{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }} usage is over 98%."
        playbook: 'docs/support/playbook/kubernetes/pvc_usage'
      annotations:
        description: "The PVC {{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }} is full. Programs will stop working if relying upon free storage."
        summary: "PVC {{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }} usage is over 98%."
