groups:
- name: controlplane-gardener
  rules:

### Gardener ###

{{- if not (.Values.prometheusRules.disabled.ShootReconciliationFailed | default false) }}
  - alert: ShootReconciliationFailed
    expr: >
      min_over_time(
      (
        (
          label_replace(
            label_replace(
              label_replace(
                garden_shoot_operation_states{operation="Reconcile"},
                "support_group","containers","__name__",".*"
              ),
              "support_group","storage","project","^storage$"
            ),
            "support_group","compute","project","^compute$"
          ) != 1
        )
        OR
        (
          label_replace(
            label_replace(
              label_replace(
                garden_shoot_operation_states{operation="Reconcile"},
                "support_group","containers","__name__",".*"
              ),
              "support_group","storage","project","^storage$"
            ),
            "support_group","compute","project","^compute$"
          ) != 2
        )
      )
      [{{ dig "ShootReconciliationFailed" "for" "30m" .Values.prometheusRules }}:]
      ) != 1
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "ShootReconciliationFailed" "severity" "warning" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/ShootReconciliationFailed.md
      service: gardener
      support_group: "{{`{{ $labels.support_group }}`}}"
    annotations:
      description: Shoot {{`{{ $labels.name }}`}} from project {{`{{ $labels.project }}`}} on {{`{{ $labels.landscape }}`}} is not being reconciled successfully for {{ dig "ShootReconciliationFailed" "for" "30m" .Values.prometheusRules }} minutes. Check the shoot's conditions and events for more details.
      summary: Shoot {{`{{ $labels.name }}`}} on {{`{{ $labels.landscape }}`}} is not being reconciled successfully.
{{- end }}

{{- if not (.Values.prometheusRules.disabled.ShootConditionNotTrue | default false) }}
  - alert: ShootConditionNotTrue
    expr: >
      max by (project, landscape, seed, name, support_group) (
        (
          label_replace(
            label_replace(
              label_replace(
                garden_shoot_condition,
                "support_group", "containers", "__name__", ".*"
              ),
              "support_group", "storage", "project", "^storage$"
            ),
            "support_group", "compute", "project", "^compute$"
          )
        ) != 1
      )
    for: {{ dig "ShootConditionNotTrue" "for" "30m" .Values.prometheusRules }}
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "ShootConditionNotTrue" "severity" "warning" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/ShootConditionNotTrue.md
      service: gardener
      support_group: "{{`{{ $labels.support_group }}`}}"
    annotations:
      description: Shoot {{`{{ $labels.name }}`}} of project {{`{{ $labels.project }}`}} seeded from {{`{{ $labels.landscape }}`}}/{{`{{ $labels.seed }}`}} has a condition that is not True. Check the Shoot's conditions and events for more details.
      summary: Shoot {{`{{ $labels.name }}`}} seeded from {{`{{ $labels.seed }}`}} has a condition that is not True.
{{- end }}

{{- if not (.Values.prometheusRules.disabled.SeedConditionNotTrue | default false) }}
  - alert: SeedConditionNotTrue
    expr: >
      max by (landscape, name, support_group) (
        (
          label_replace(
            label_replace(
              label_replace(
                garden_shoot_condition{is_seed="true"},
                "support_group", "containers", "__name__", ".*"
              ),
              "support_group", "storage", "project", "^storage$"
            ),
            "support_group", "compute", "project", "^compute$"
          )
        ) != 1
      )
    for: {{ dig "SeedConditionNotTrue" "for" "30m" .Values.prometheusRules }}
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "SeedConditionNotTrue" "severity" "warning" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/SeedConditionNotTrue.md
      service: gardener
      support_group: "{{`{{ $labels.support_group }}`}}"
    annotations:
      description: Seed {{`{{ $labels.name }}`}} on {{`{{ $labels.landscape }}`}} has a condition that is not True. Check the Seed's conditions and events for more details.
      summary: Seed {{`{{ $labels.name }}`}} on {{`{{ $labels.landscape }}`}} has a condition that is not True.
{{- end }}

{{- if not (.Values.prometheusRules.disabled.GardenNotReady | default false) }}
  - alert: GardenNotReady
    expr: max by(landscape) (garden_garden_condition{status="True"}) != 1
    for: {{ dig "GardenNotReady" "for" "30m" .Values.prometheusRules }}
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "GardenNotReady" "severity" "warning" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/GardenNotReady.md
      service: gardener
      support_group: {{ dig "GardenNotReady" "support_group" .Values.prometheusRules.defaultSupportGroup .Values.prometheusRules }}
    annotations:
      description: Gardenlet on {{`{{ $labels.landscape }}`}} is not Ready. Check the Gardenlet's conditions and events for more details.
      summary: Gardenlet on {{`{{ $labels.landscape }}`}} is not Ready.
{{- end }}

### Calico ###

{{- if not (.Values.prometheusRules.disabled.CalicoBgpNeighborSessionDown | default false) }}
  - alert: CalicoBgpNeighborSessionDown
    expr: >
      sum by (cluster, node, pod, support_group) (
        label_replace(
          label_replace(
            label_replace(
              bird_protocol_up{proto="BGP", state="Established"},
              "support_group", "containers", "__name__", ".*"
            ),
            "support_group", "storage", "project", "^storage$"
          ),
          "support_group", "compute", "project", "^compute$"
        )
      )
      <
      {{ .Values.prometheusRules.calico.bgpNeighborCount }}
    for: {{ dig "CalicoBgpNeighborSessionDown" "for" "30m" .Values.prometheusRules }}
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "CalicoBgpNeighborSessionDown" "severity" "warning" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/CalicoBgpNeighborSessionDown.md
      service: calico
      support_group: "{{`{{ $labels.support_group }}`}}"
    annotations:
      description: Calico Node Pod {{`{{ $labels.pod }}`}} on Shoot/Node {{trimPrefix "shoot--cp--" "`{{ $labels.cluster }}`"}}/{{`{{ $labels.node }}`}} has less than {{ .Values.prometheusRules.calico.bgpNeighborCount }} BGP neighbors. BGP peer is not established. Network datapath threatened! Switch upgrades or misconfiguration?
      summary: Calico Node Pod {{`{{ $labels.pod }}`}} on Shoot {{trimPrefix "shoot--cp--" "`{{ $labels.cluster }}`"}} has less than {{ .Values.prometheusRules.calico.bgpNeighborCount }} BGP neighbors.
{{- end }}

{{- if not (.Values.prometheusRules.disabled.CalicoBgpNeighborSessionAllDown | default false) }}
  - alert: CalicoBgpNeighborSessionAllDown
    expr: >
      sum by (cluster, node, pod, support_group) (
        label_replace(
          label_replace(
            label_replace(
              bird_protocol_up{proto="BGP", state="Established"},
              "support_group", "containers", "__name__", ".*"
            ),
            "support_group", "storage", "project", "^storage$"
          ),
          "support_group", "compute", "project", "^compute$"
        )
      )
      == 0
    for: {{ dig "CalicoBgpNeighborSessionAllDown" "for" "10m" .Values.prometheusRules }}
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "CalicoBgpNeighborSessionAllDown" "severity" "warning" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/CalicoBgpNeighborSessionAllDown.md
      service: calico
      support_group: "{{`{{ $labels.support_group }}`}}"
    annotations:
        description: Calico Node Pod {{`{{ $labels.pod }}`}} on Shoot/Node {{trimPrefix "shoot--cp--" "`{{ $labels.cluster }}`"}}/{{`{{ $labels.node }}`}} has no BGP neighbors. Network datapath is down! Switch upgrades or misconfiguration?
        summary: Calico Node Pod {{`{{ $labels.pod }}`}} on Shoot {{trimPrefix "shoot--cp--" "`{{ $labels.cluster }}`"}} has no BGP neighbors.
{{- end }}

{{- if not (.Values.prometheusRules.disabled.CalicoNodeMissing | default false) }}
  - alert: CalicoNodeMissing
    expr: count(up{job="kubelet"}) > count(_pod_to_daemonset{owner_name="calico-node"} == 1)
    for: {{ dig "CalicoNodeMissing" "for" "30m" .Values.prometheusRules }}
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "CalicoNodeMissing" "severity" "warning" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/CalicoNodeMissing.md
      service: calico
      support_group: {{ dig "CalicoNodeMissing" "support_group" .Values.prometheusRules.defaultSupportGroup .Values.prometheusRules }}
    annotations:
        description: Calico is not running on all BareMetal nodes. Network datapath threatened!
        summary: Calico is not running on all BareMetal nodes.
{{- end }}

{{- if not (.Values.prometheusRules.disabled.CalicoNodeNotReady | default false) }}
  - alert: CalicoNodeNotReady
    expr: >
      label_replace(
        label_replace(
          label_replace(
            kube_pod_status_ready{
              namespace = "kube-system",
              pod       =~ "calico-node-[a-zA-Z0-9]{5}",
              condition = "false",
              type      = "shoot"
            },
            "support_group", "containers", "__name__", ".*"
          ),
          "support_group", "storage", "project", "^storage$"
        ),
        "support_group", "compute", "project", "^compute$"
      ) == 1
    for: {{ dig "CalicoNodeNotReady" "for" "30m" .Values.prometheusRules }}
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "CalicoNodeNotReady" "severity" "warning" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/CalicoNodeNotReady.md
      service: calico
      support_group: "{{`{{ $labels.support_group }}`}}"
    annotations:
      description: Calico Node Pod {{`{{ $labels.pod }}`}} on Shoot {{`{{ $labels.shoot_name }}`}} is not Ready. Network datapath threatened!
      summary: Calico Node Pod {{`{{ $labels.pod }}`}} on Shoot {{`{{ $labels.shoot_name }}`}} is not Ready.
{{- end }}

### MCM ###

{{- if not (.Values.prometheusRules.disabled.MCMMachineNotReady | default false) }}
  - alert: MCMMachineNotReady
    expr: >
      sum by (name, project, shoot_name, support_group) (
        label_replace(
          label_replace(
            label_replace(
              mcm_machine_status_condition{
                job="machine-controller-manager",
                condition="Ready"
              },
              "support_group", "containers", "__name__", ".*"
            ),
            "support_group", "storage", "project", "^storage$"
          ),
          "support_group", "compute", "project", "^compute$"
        )
      ) == 0
    for: {{ dig "MCMMachineNotReady" "for" "30m" .Values.prometheusRules }}
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "MCMMachineNotReady" "severity" "warning" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/MCMMachineNotReady.md
      service: gardener
      support_group: "{{`{{ $labels.support_group }}`}}"
    annotations:
      description: Machine {{`{{ $labels.name }}`}} from Shoot {{`{{ $labels.shoot_name }}`}} of project {{`{{ $labels.project }}`}} is not Ready. Check the Machine's conditions and events for more details.
      summary: Machine {{`{{ $labels.name }}`}} from Shoot {{`{{ $labels.shoot_name }}`}} is not Ready.
{{- end }}

{{- if not (.Values.prometheusRules.disabled.MCMMachineStuckInTerminating | default false) }}
  - alert: MCMMachineStuckInTerminating
    expr: >
      sum by (name, project, shoot_name, support_group) (
        label_replace(
          label_replace(
            label_replace(
              mcm_machine_current_status_phase{
                job="machine-controller-manager",
              },
              "support_group", "containers", "__name__", ".*"
            ),
            "support_group", "storage", "project", "^storage$"
          ),
          "support_group", "compute", "project", "^compute$"
        )
      ) == -4
    for: {{ dig "MCMMachineStuckInTerminating" "for" "30m" .Values.prometheusRules }}
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "MCMMachineStuckInTerminating" "severity" "warning" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/MCMMachineStuckInTerminating.md
      service: gardener
      support_group: "{{`{{ $labels.support_group }}`}}"
    annotations:
      description: Machine {{`{{ $labels.name }}`}} from Shoot {{`{{ $labels.shoot_name }}`}} of project {{`{{ $labels.project }}`}} is stuck in Terminating state. Check the Machine's conditions and events for more details.
      summary: Machine {{`{{ $labels.name }}`}} from Shoot {{`{{ $labels.shoot_name }}`}} is stuck in Terminating state.
{{- end }}

{{- if not (.Values.prometheusRules.disabled.MCMMachineFailed | default false) }}
  - alert: MCMMachineFailed
    expr: >
      sum by (name, project, shoot_name, support_group) (
        label_replace(
          label_replace(
            label_replace(
              mcm_machine_current_status_phase{
                job="machine-controller-manager",
              },
              "support_group", "containers", "__name__", ".*"
            ),
            "support_group", "storage", "project", "^storage$"
          ),
          "support_group", "compute", "project", "^compute$"
        )
      ) == -3
    for: {{ dig "MCMMachineFailed" "for" "30m" .Values.prometheusRules }}
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "MCMMachineFailed" "severity" "warning" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/MCMMachineFailed.md
      service: gardener
      support_group: "{{`{{ $labels.support_group }}`}}"
    annotations:
      description: Machine {{`{{ $labels.name }}`}} from Shoot {{`{{ $labels.shoot_name }}`}} of project {{`{{ $labels.project }}`}} is in Failed state. Check the Machine's conditions and events for more details.
      summary: Machine {{`{{ $labels.name }}`}} from Shoot {{`{{ $labels.shoot_name }}`}} is in Failed state.
{{- end }}

{{- if not (.Values.prometheusRules.disabled.MCMMachineCrashLoopBackOff | default false) }}
  - alert: MCMMachineCrashLoopBackOff
    expr: >
      sum by (name, project, shoot_name, support_group) (
        label_replace(
          label_replace(
            label_replace(
              mcm_machine_current_status_phase{
                job="machine-controller-manager",
              },
              "support_group", "containers", "__name__", ".*"
            ),
            "support_group", "storage", "project", "^storage$"
          ),
          "support_group", "compute", "project", "^compute$"
        )
      ) == -2
    for: {{ dig "MCMMachineCrashLoopBackOff" "for" "30m" .Values.prometheusRules }}
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "MCMMachineCrashLoopBackOff" "severity" "warning" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/MCMMachineCrashLoopBackOff.md
      service: gardener
      support_group: "{{`{{ $labels.support_group }}`}}"
    annotations:
      description: Machine {{`{{ $labels.name }}`}} from Shoot {{`{{ $labels.shoot_name }}`}} of project {{`{{ $labels.project }}`}} is in CrashLoopBackOff state. Check the Machine's conditions and events for more details.
      summary: Machine {{`{{ $labels.name }}`}} from Shoot {{`{{ $labels.shoot_name }}`}} is in CrashLoopBackOff state.
{{- end }}

{{- if not (.Values.prometheusRules.disabled.MCMMachineStuckInPending | default false) }}
  - alert: MCMMachineStuckInPending
    expr: >
      sum by (name, project, shoot_name, support_group) (
        label_replace(
          label_replace(
            label_replace(
              mcm_machine_current_status_phase{
                job="machine-controller-manager",
              },
              "support_group", "containers", "__name__", ".*"
            ),
            "support_group", "storage", "project", "^storage$"
          ),
          "support_group", "compute", "project", "^compute$"
        )
      ) == 0
    for: {{ dig "MCMMachineStuckInPending" "for" "30m" .Values.prometheusRules }}
    labels:
      {{ include "controlplane-operations.additionalRuleLabels" . }}
      severity: {{ dig "MCMMachineStuckInPending" "severity" "warning" .Values.prometheusRules }}
      playbook: https://github.com/cobaltcore-dev/controlplane-operations/playbooks/MCMMachineStuckInPending.md
      service: gardener
      support_group: "{{`{{ $labels.support_group }}`}}"
    annotations:
      description: Machine {{`{{ $labels.name }}`}} from Shoot {{`{{ $labels.shoot_name }}`}} of project {{`{{ $labels.project }}`}} is stuck in Pending state. Check the Machine's conditions and events for more details.
      summary: Machine {{`{{ $labels.name }}`}} from Shoot {{`{{ $labels.shoot_name }}`}} is stuck in Pending state.
{{- end }}
